using System.Text.RegularExpressions;
using BaseLib.Abstracts;
using Godot;
using Theresa.TheresaCode.Extensions;

namespace Theresa.TheresaCode.Powers;

public abstract partial class TheresaPowerModel : CustomPowerModel
{
    private static readonly Regex CamelCaseRegex = MyRegex();

    // 根据类名自动生成唯一的 Power ID (例如, "MyGreatPower" -> "my_great_power")
    protected virtual string PowerId => CamelCaseRegex.Replace(GetType().Name, "$1_$2").ToLowerInvariant();

    // 根据 Power ID 构建图标的基本路径
    protected virtual string IconBasePath => $"res://Theresa/images/powers/{PowerId}.png";

    public override string? CustomPackedIconPath => SafeGetIconPath();
    public override string? CustomBigIconPath => SafeGetIconPath();

    /// <summary>
    /// 安全地获取图标路径。首先尝试使用基于类名自动生成的路径，
    /// 如果该路径下的资源不存在，则回退到默认图标。
    /// </summary>
    /// <returns>有效的图标路径</returns>
    protected virtual string SafeGetIconPath()
    {
        // 首先尝试使用自动生成的路径
        string autoGeneratedPath = IconBasePath;

        // 检查自动生成的路径是否存在
        // 如果存在，就使用它；如果不存在（比如忘了做图），就回退到默认图标
        return ResourceLoader.Exists(autoGeneratedPath) ? autoGeneratedPath : "power.png".BigPowerImagePath();
    }

    [GeneratedRegex(@"([a-z])([A-Z])", RegexOptions.Compiled)]
    private static partial Regex MyRegex();
}